### ISSUE TITLE
No prop for customization of outer div

### ISSUE THREAD

**Issue by juniorbatistaRD** [ankeetmaini/react-infinite-scroll-component#180]
This provoke styling issue when the parent dom element need custom styles.

Here for example I tried to make the component  width 100% but the class name is not apply to the outer div.
 
![image](https://user-images.githubusercontent.com/31187922/77483719-39153280-6dff-11ea-8e48-607f6c596e46.png)

**Comment by deepal** [comment]
Yeah, this is painful. All I could do was adding a style like this to override it:

```css
.infinite-scroll-component__outerdiv {
     width: 100%
}
```
