### ISSUE TITLE
Hide scroll bar but allow scrolling?

### ISSUE THREAD

**Issue by tobiaskatch** [ankeetmaini/react-infinite-scroll-component#317]
Hello, 

is there a way to allow scolling while hiding the scroll bar? I tried applying the standard styles for hiding scroll bar (which works with any other scroll component):

.scroll-style {
    scrollbar-width: none; /* Firefox */
    -ms-overflow-style: none;  /* Internet Explorer 10+ */
}
.scroll-style::-webkit-scrollbar { /* WebKit */
    width: 0;
    height: 0;
}

But this does not work for the infinite scroll component. Also setting style "overflow" to hidden does not work. 
I think it would be very nice if there was a way of hiding the scroll bar as it would look better in many applications and avoid a"jumping" scroll bar when fetching data. 

Kind regards.

**Comment by devjs1000** [comment]
### you can use this to help 

1. set the property to initial `all:initial;` in scroll bar
2. don't forget to use force apply use `!important` in the css for overriding
3. Now you can style scroll bar as your wish

**Comment by iamdarshshah** [comment]
The scrollbar-hiding CSS needs to target the inner scroll container, which has the class `infinite-scroll-component`:

```css
.infinite-scroll-component {
  scrollbar-width: none;        /* Firefox */
  -ms-overflow-style: none;     /* IE 10+ */
}
.infinite-scroll-component::-webkit-scrollbar {
  display: none;                /* Chrome, Safari, Edge */
}
```

You can also pass it inline via the `style` prop:

```jsx
<InfiniteScroll style={{ msOverflowStyle: 'none', scrollbarWidth: 'none' }} ...>
```

Note: hiding the scrollbar with `overflow: hidden` will prevent scrolling entirely, so use `scrollbar-width: none` or `::-webkit-scrollbar { display: none }` instead.

Does that help? Happy to answer follow-up questions.
